### ISSUE TITLE
[Android Bootcamp] Group Milestone - Implementation (Sprint 1) - Review

### ISSUE THREAD

**Issue by danielhochman** [izd/kiva#18]
[.gif walkthrough](http://i.imgur.com/2ImNzfO.gif)

**Comment by danielhochman** [comment]
Sprint complete, please review. /cc @codepathreview @codepath

**Comment by codepathreview** [comment]
:+1:  Excellent work creating neat wire-frames and creating stories. Great to see the basic screens and flow coming along well. Few notes to mention:
- Good to see the wireframes that cover basic flow of the app
- Good job identifying required and optional user stories
- Good work on organizing the codebase properly, makes it easier for you and everyone in team to find stuff easily
- Well created detailed stories/tasks on the project wiki. Good to see you created milestones and assigned issues to them.
- Nice way of splitting a parent task into a number of smaller subtasks - provides a better picture of the progress on the issue.
- Good job by everyone to [contribute](https://github.com/izd/kiva/graphs/contributors) to the project. But the work load needs to be divided equally among all members of the team. This is critical in working as a team and also gives equal learning opportunity to everyone involved. Looking at the graph it seems one member is contributing way more than others, pls feel free to correct me if that is not the case.
- Good to see that your team created regular commits to sync up your code to avoid having multiple conflicts at the end.
- Consider creating tasks to QA the app a few times to check the basic flow. Integration testing will especially be important for this project since each team member is working on a separate module. The best part is seeing it all come together into a polished app.
- Good to see you guys create pull requests frequently, helps better track your progress and review each others code.

Good to see the basic flow coming along well. Please take notes of these points and improve upon the same in the next sprint. Look forward to the rest of the functionality and improvement on the core flows by the end of the Sprint 2 so you can have enough time to add UI polish and advanced nice-to-have features later on. It is those little extra things you do that make everything feel more polished and desirable to use.
